from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import utils
from reportlab.lib.units import inch
from datetime import datetime

# Get the current local date and time
current_datetime = datetime.now()

# Get the local date
current_date = current_datetime.date()

# Get the local time
current_time = current_datetime.time()

formatted_time = current_time.strftime("%H.%M.%S")

# Create a PDF document
patient_name = "aa"
pdf_filename = "diagnosis_report-" + patient_name + "_" + str(formatted_time) + ".pdf"
document = SimpleDocTemplate(pdf_filename, pagesize=letter)

# Sample data - replace this with your own patient and blood test information
Diagnosis = ""
Patient_ID = ""
Date = current_date
Time = current_time
results = ""
Disclaimer = ("**The report is generated by the AI model and the results are not 100% accurate."
              "Please consult a doctor for further diagnosis.**")

# Sample image path - replace this with the path to your hospital logo
webApplication_logo_path = "CraniumCryptics_Logo.png"

# Styles for the document
styles = getSampleStyleSheet()

# Custom styles for the report
title_style = ParagraphStyle('Title', parent=styles['Title'], fontSize=18, spaceAfter=12)
subtitle_style = ParagraphStyle('Subtitle', parent=styles['Title'], fontSize=14, textColor=colors.gray)
body_style = ParagraphStyle('BodyText', parent=styles['BodyText'], spaceAfter=12)

# Content to be added to the PDF
content = []

# Add hospital logo
# logo = Image(webApplication_logo_path, width=150, height=50)
# content.append(logo)
# content.append("CrainiumCryptics")



# Create a table for the header
header_table_data = [
    [Image(webApplication_logo_path, width=150, height=50), Paragraph(f"Patient: {patient_name}<br/>"
                                                                      f"Patient ID: {Patient_ID}"
                                                                      f"<br/>Date: {current_date}"
                                                                      f"<br/>Time: {current_time}", subtitle_style)],
]

header_table_style = [
    ('ALIGN', (0, 0), (0, 0), 'LEFT'),
    ('VALIGN', (0, 0), (0, 0), 'MIDDLE'),
]

header_table = Table(header_table_data, colWidths=[300, 200])
header_table.setStyle(header_table_style)

content.append(header_table)




# Add title
title = Paragraph("Diagnosis Report", title_style)
content.append(title)

# Add patient information
patient_info = Paragraph(f"Patient: {patient_name}<br/>Patient ID: {Patient_ID}", subtitle_style)
content.append(patient_info)

# Add space
content.append(Spacer(1, 12))

# Add image
uploaded_image_path = "testUploadImage.jpg"
uploaded_image = Image(uploaded_image_path, width=250, height=250)
content.append(uploaded_image)

# Add space
content.append(Spacer(3, 12))

# Add diagnosis results
results_title = Paragraph("Diagnosis Results: " + Diagnosis, subtitle_style)
content.append(results_title)

# Add space
content.append(Spacer(10, 100))

# Add disclaimer
disclaimer = Paragraph(Disclaimer, body_style)
content.append(disclaimer)

# Build the PDF document
document.build(content)
