from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib import colors
from datetime import datetime


def generate_pdf(user_name, user_email):
    # Create a PDF document
    doc = SimpleDocTemplate("diagnosis_report.pdf", pagesize=letter)

    # Define styles
    header_style = ParagraphStyle(
        "header",
        fontSize=12,
        textColor=colors.white,
        alignment=1,  # Center alignment
        leftIndent=6,
        spaceAfter=6,
        background=colors.HexColor('#789798'),
    )
    footer_style = ParagraphStyle(
        "footer",
        fontSize=10,
        textColor=colors.black,
        alignment=1,  # Center alignment
        spaceAfter=6,
    )

    # Header content
    header_content = Paragraph(
        f'<img src="reportLogo.png" width="100" height="100"/> <br/><b>Your Hospital Name</b>',
        header_style,
    )

    # Footer content
    footer_content = Paragraph(
        '<br/><br/>**The report is generated by the AI model and the results are not 100% accurate. Please consult a doctor for further diagnosis.**',
        footer_style,
    )

    # Current date and time
    current_date = datetime.now().strftime("%Y-%m-%d")
    current_time = datetime.now().strftime("%H:%M:%S")
    user_info = f"User: {user_name}<br/>Email: {user_email}<br/>Date: {current_date}<br/>Time: {current_time}"
    user_info_para = Paragraph(user_info, footer_style)

    # Main content
    main_content = [
        Spacer(1, 12),
        Paragraph("<b>Diagnosis Report</b>", header_style),  # Center alignment
        Spacer(1, 12),
        Image("img.png", width=400, height=400),
        Spacer(1, 12),
        Paragraph("Edge Detected status: Detected", header_style),  # Center alignment
        Paragraph("Tumor Detected status: Detected", header_style),  # Center alignment
        Paragraph("Detected Tumour type: Detected", header_style),  # Center alignment
        Paragraph("Alzheimer Detected status: Detected", header_style),  # Center alignment
        Paragraph("Stroke Detected Status: Detected", header_style),  # Center alignment
    ]

    # Build the document
    doc.build([header_content, user_info_para] + main_content + [footer_content])


# Example usage
generate_pdf("John Doe", "john.doe@example.com")
