from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, PageBreak
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from datetime import datetime

# Get the current local date and time
current_datetime = datetime.now()

# Get the local date
current_date = current_datetime.date()

# Get the local time
current_time = current_datetime.time()

formatted_time = current_time.strftime("%H.%M.%S")

# Create a PDF document with A4 size
pdf_filename = "diagnosis_report_" + formatted_time + ".pdf"
document = SimpleDocTemplate(pdf_filename, pagesize=A4,
                              leftMargin=inch, rightMargin=inch, topMargin=inch, bottomMargin=inch,
                              borderWidth=1, borderColor=colors.black)

# Sample data - replace this with your own patient and blood test information
patient_name = "Uzman Arfan"
Diagnosis = "Put the diagnosis here."
Patient_ID = "12345"
results = ""
Disclaimer = ("**The report is generated by the AI model and the results are not 100% accurate. "
              "Please consult a doctor for further diagnosis.**")

# Sample image path - replace this with the path to your hospital logo
webApplication_logo_path = "reportLogo.png"

# Styles for the document
styles = getSampleStyleSheet()

# Custom styles for the report
title_style = ParagraphStyle('Title', parent=styles['Title'], fontSize=18, spaceAfter=12)
subtitle_style = ParagraphStyle('Subtitle', parent=styles['Title'], fontSize=14, textColor=colors.gray, alignment=0)  # Alignment set to left
body_style = ParagraphStyle('BodyText', parent=styles['BodyText'], spaceAfter=12)

# Content to be added to the PDF
content = []

# Add header content
header_table_data = [
    [Image(webApplication_logo_path, width=150, height=50), Paragraph(f"Patient: {patient_name}<br/>"
                                                                      f"Patient ID: {Patient_ID}"
                                                                      f"<br/>Date: {current_date}"
                                                                      f"<br/>Time: {current_time}", subtitle_style)],
]
header_table = Table(header_table_data, colWidths=[300, 200])
content.append(header_table)

# Add section line
section_line = Paragraph("<hr width='100%' size='1' color='black'/>", styles["Normal"])
content.append(section_line)

# Add body content
body_content = [
    Spacer(1, 12),
    Paragraph("Diagnosis Report", title_style),
    Spacer(1, 12),
    Paragraph(f"Diagnosis Results: {Diagnosis}", subtitle_style),
    Spacer(10, 100),
    Paragraph(Disclaimer, body_style),
]
content.extend(body_content)

# Add footer content
footer_content = [
    Spacer(1, 12),
    Paragraph("Your Footer Content Here", subtitle_style),  # Replace with your footer content
]
content.extend(footer_content)

# Build the PDF document
document.build(content)